### ISSUE TITLE
Idea: render "simple" lists on one line

### ISSUE THREAD

**Issue by Yura52** [hukkin/tomli-w#25]
Hi! Below, I provide (A) the output of the latest Tomli-W and (B) what I propose for "simple" lists (i.e. those containing only literal values: booleans, numbers, strings, time). The data is a subset of my real TOML file, only keys and strings are replaced with dummy values. In general, I agree with the current "conservative" approach, but it looks like the chance of getting readable output for "simple" lists will be higher with the proposed approach. To avoid too long lines, the length limit similar to [this one](MAX_LINE_LENGTH) can be introduced.

```toml
# (A)
[a]
b = [
    "k1",
    8,
    512,
]

[c]
d = [
    "k2",
    1,
    8,
    16,
    1024,
]
e = [
    "k3",
    0.0,
    0.0,
    0.5,
]

[f]
g = [
    "k4",
    5e-05,
    0.005,
]
h = [
    "k5",
    1e-06,
    0.001,
]

# (B)
[a]
b = ["k1", 8, 512]

[c]
d = ["k2", 1, 8, 16, 1024]
e = ["k3", 0.0, 0.0, 0.5]

[f]
g = ["k4", 5e-05, 0.005]
h = ["k5", 1e-06, 0.001]
```

**Comment by hukkin** [comment]
Thanks for the issue!

I'm not sure that I want this. Using exploded arrays always is a simpler rule and results in smaller diffs when items are added or removed.

Yes, we did merge a comparable style related PR https://github.com/hukkin/tomli-w/pull/15 earlier, but that was because A) we were printing style explicitly discouraged by TOML spec and B) I'm still not sure if even that was really necessary. :smile: 

Our input data does not contain style information so any new style improving features mean we have to inspect the data and there's always a performance cost. Also the more rules we add, the more interplay the rules will have with each other: for instance https://github.com/hukkin/tomli-w/pull/15 makes choices based on the assumption that arrays are multi-line, and this feature would make that a less accurate assumption.

If style is important to you, I do recommend looking up tomlkit or atoml (a fork of tomlkit).

**Comment by FObersteiner** [comment]
Since this is still open: [atoml](https://github.com/frostming/atoml) is archived, so [tomlkit](https://github.com/sdispater/tomlkit) seems to be the way to go.

**Comment by hukkin** [comment]
I have no plans for this right now so I'll close. I may revisit the idea when/if https://github.com/hukkin/tomli-w/issues/59 happens.
