### ISSUE TITLE
`tomli_w.dump` needs output stream to be opened in binary mode

### ISSUE THREAD

**Issue by amotl** [hukkin/tomli-w#40]
Hi again,

while working on the test case [1] to outline #39, we also found that, when using the access pattern to directly serialize to a file,
```python
with open("testdrive.toml", "wb") as config_file:
    tomli_w.dump(data, config_file)
```

`tomli_w.dump` needs the file to be opened in binary mode (`wb`) and croaks otherwise. Both the other libraries `toml` and `tomlkit` do not have that requirement and work well when opening the output stream in text mode (`w`).

Do you see a chance to adjust `tomli-w` accordingly?

With kind regards,
Andreas.

[1] https://gist.github.com/amotl/4d8bc928d781a5d0fbc7f404396f8417

**Comment by hukkin** [comment]
Hi, thanks for the issue!

I'm inclined to not allow text mode due to:
- consistency with `tomli` the read-only module
- in text mode, encoding becomes platform dependent but TOML strictly requires UTF-8, allowing users to write invalid TOML
- line separator becomes platform independent. If the platform uses carriage return as line separator, users will write invalid TOML

I.e. allowing text mode is a footgun that I think we can manage without.

**Comment by amotl** [comment]
Dear Taneli,

thank you very much for taking the time to respond to my request and for providing a rationale why `tomli-w` does it just right.

With kind regards,
Andreas.
